version: "3.9"

services:
  db:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=testpass
      - MYSQL_DATABASE=default
    volumes:
    - devmysqldb:/var/lib/mysql

  backend: 
    build: backend 
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend:/app
    stdin_open: true # enable attach for pdb
    ports: 
      - '8000:80'
  
  frontend:
    build: frontend
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend:/frontend
    ports:
      - "8090:80"

volumes:
  devmysqldb: