version: "3.9"

services:
  db:
    image: mariadb:10.5.8
    environment:
      - MYSQL_ROOT_PASSWORD=testpass
      - MYSQL_DATABASE=default
    volumes:
    - devmysqldb:/var/lib/mysql

  service: 
    build: app 
    depends_on:
      - db
    volumes:
      - ./app:/app
    stdin_open: true # enable attach for pdb
    ports: 
      - '5000:5000'
volumes:
  devmysqldb: